### ISSUE TITLE
Default ValueObject values

### ISSUE THREAD

**Issue by skyrpex** [spatie/value-object#19]
Hi there! 👋 

Have you considered allowing default values in the ValueObjects? Maybe it's not even a good practice... 🤷‍♂️ .

```php
class QueryOptions extends ValueObject
{
    /** @var string */
    public $query = '';

    /** @var int */
    public $page;
}

// This actually throws because query is null, but it could just take the default value.
new QueryOptions([
    'page' => 1,
]);
```

It's specially helpful when working with Laravel's request validation.

**Comment by brendt** [comment]
@skyrpex overriding the constructor seems like the way to go. I think this is the better approach, because you cannot set all types of values directly to the property, so you're stuck with the constructor anyway, in some cases.
