### ISSUE TITLE
meta object for key auto-completion

### ISSUE THREAD

**Issue by voku** [spatie/value-object#28]
Hi, what do you think of an meta-oject, where we can get the keys, so that you don't need to use strings for this...

e.g.: 
```php
$postMeta = PostData::meta();
$postData = new PostData([
    $postMeta->title => '…',
    $postMeta->body => '…',
    $postMeta->author_id => '…',
]);
```

**Comment by brendt** [comment]
I tend to use static constructors to handle autocompletion.

```php
PostData::create($title, $body, $author);
```

I don't think it's worth the overhead just for the sake of autocompletion.
