### ISSUE TITLE
Better exception support

### ISSUE THREAD

**Issue by brendt** [spatie/value-object#9]
Right now, `ValueObjectException` extends `\Exception`.

It would be good to extend `\TypeError` instead, this allows the package to be more in line with the upcoming 7.4 type system.

Also, we should pass the property itself instead of its name and class. For example:

```php
public static function invalidType(
        string $propertyName,
        string $className,
        string $expectedType,
        $value
    )
```

Becomes

```php
public static function invalidType(Property $property, $value)
```

Of course, the needed helper methods may be added on `Property`.

**Comment by belushkin** [comment]
let me check it

**Comment by brendt** [comment]
Sorry, already did it!
